name: Index Librexam Test Repositories

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  index-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch librexam-test repositories
        id: fetch
        run: |
          echo "Fetching repos with topic: librexam-test"
          curl -s "https://api.github.com/search/repositories?q=topic:librexam-test&sort=updated&order=desc&per_page=100" \
            -H "Accept: application/vnd.github+json" \
            | jq '{fetched_at: now | todate, total_count, repositories: [.items[] | {
                name,
                full_name,
                html_url,
                description,
                owner: .owner.login,
                updated_at,
                stargazers_count
              }]}' > indexedRepos.json

      - name: Show diff (if any)
        run: |
          git diff --stat || echo "No changes detected."

      - name: Commit & Push changes (if any)
        run: |
          git config user.name "librexam-bot"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add indexedRepos.json
            git commit -m "Update indexedRepos.json on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
