name: Index Librexam Test Repositories

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  index-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Fetch librexam-test repositories
        id: fetch
        run: |
          echo "Fetching repos with topic: librexam-test"
          curl -s "https://api.github.com/search/repositories?q=topic:librexam-test&sort=updated&order=desc&per_page=100" \
            -H "Accept: application/vnd.github+json" > repos.json

          jq -r '.items[] | [.full_name, .name, .html_url, .description, .owner.login, .stargazers_count] | @tsv' repos.json > raw_repos.tsv

          echo '{ "fetched_at": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'", "total_count": '$(wc -l < raw_repos.tsv)', "repositories": [' > indexedRepos.json

          FIRST=true

          while IFS=$'\t' read -r full_name name html_url description owner stargazers; do
            latest_commit=$(curl -s "https://api.github.com/repos/$full_name/commits?per_page=1" \
              -H "Accept: application/vnd.github+json" | jq -r '.[0].commit.author.date // empty')

            if [ -z "$latest_commit" ]; then
              latest_commit=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            fi

            if [ "$FIRST" = true ]; then
              FIRST=false
            else
              echo ',' >> indexedRepos.json
            fi

            jq -n --arg name "$name" \
                  --arg full_name "$full_name" \
                  --arg html_url "$html_url" \
                  --arg description "$description" \
                  --arg owner "$owner" \
                  --arg updated_at "$latest_commit" \
                  --arg stars "$stargazers" \
            '{
              name: $name,
              full_name: $full_name,
              html_url: $html_url,
              description: $description,
              owner: $owner,
              updated_at: $updated_at,
              stargazers_count: ($stars | tonumber)
            }' >> indexedRepos.json
          done < raw_repos.tsv

          echo '] }' >> indexedRepos.json

      - name: Show diff (if any)
        run: |
          git diff --stat || echo "No changes detected."

      - name: Commit & Push changes (if any)
        run: |
          git config user.name "librexam-bot"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add indexedRepos.json
            git commit -m "Update indexedRepos.json on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
